name: zeus.go
description: "Projeto gerenciamento de estoque."

publish_to: 'Mateus "ZeUs" Ferreira Kroning' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  get: ^4.6.5
  shared_preferences: ^2.0.15
  sqflite: ^2.3.3+1
  path: ^1.9.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  flutter_gen:
  build_runner:
  package_info_plus: ^8.0.2
  cpf_cnpj_validator:
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.3.0

  flutter_lints: ^3.0.0

flutter:
  generate: true

  uses-material-design: true
  assets: 
   - assets/images/4396761.png