// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUqswW9f9PLiZj2vawpjNX72fn8GyYe4',
    appId: '1:37175739616:web:7c8c00ff76b07da4ee3c85',
    messagingSenderId: '37175739616',
    projectId: 'zeus-warehouse-manager',
    authDomain: 'zeus-warehouse-manager.firebaseapp.com',
    storageBucket: 'zeus-warehouse-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6IO1xSi5Ki-08AMtEA51NYTwZygnT9M8',
    appId: '1:37175739616:android:0ef47edbab9160c2ee3c85',
    messagingSenderId: '37175739616',
    projectId: 'zeus-warehouse-manager',
    storageBucket: 'zeus-warehouse-manager.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUqswW9f9PLiZj2vawpjNX72fn8GyYe4',
    appId: '1:37175739616:web:8eaa4eb0508a4601ee3c85',
    messagingSenderId: '37175739616',
    projectId: 'zeus-warehouse-manager',
    authDomain: 'zeus-warehouse-manager.firebaseapp.com',
    storageBucket: 'zeus-warehouse-manager.appspot.com',
  );

}